version: '3.8'

services:
  # PostgreSQL 資料庫
  postgres:
    image: postgres:15
    container_name: bgg_postgres_local
    environment:
      POSTGRES_DB: bgg_rag
      POSTGRES_USER: bgg_user
      POSTGRES_PASSWORD: bgg_password
      PGUSER: bgg_user
      TZ: Asia/Taipei
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bgg_user -d bgg_rag"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bgg_network

  # MailHog - 本地 SMTP 測試伺服器
  mailhog:
    image: mailhog/mailhog:latest
    container_name: bgg_mailhog_local
    ports:
      - "1025:1025"  # SMTP port
      - "8025:8025"  # Web UI port
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog_data:/tmp
    networks:
      - bgg_network

  # BGG RAG 應用程式
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: bgg_app_local
    depends_on:
      postgres:
        condition: service_healthy
      mailhog:
        condition: service_started
    env_file:
      - .env.local
    environment:
      # 資料庫配置 (Docker 內部網路)
      DATABASE_URL: postgresql://bgg_user:bgg_password@postgres:5432/bgg_rag
    ports:
      - "5001:5000"
    volumes:
      - .:/app
      - app_data:/app/data
    networks:
      - bgg_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  mailhog_data:
  app_data:

networks:
  bgg_network:
    driver: bridge