services:
  postgresql:
    type: postgresql

  app:
    type: python
    build:
      # 使用最小化依賴，快速構建
      command: pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements.minimal.txt
    start:
      command: gunicorn --bind 0.0.0.0:$PORT --timeout 60 --workers 1 --access-logfile - --error-logfile - start_debug:app
    env:
      PORT: 5000
      FLASK_ENV: production
      TZ: Asia/Taipei
      SECRET_KEY: your-secret-key-here
      DATABASE_URL: ${POSTGRES_CONNECTION_STRING}
      OPENAI_API_KEY: your-openai-api-key-here
      CRON_SECRET_TOKEN: your-cron-secret-token-here
      # Google OAuth 設定
      GOOGLE_CLIENT_ID: your-google-client-id-here
      GOOGLE_CLIENT_SECRET: your-google-client-secret-here
      # Email 通知設定 (可選)
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USERNAME: your-email@gmail.com
      SMTP_PASSWORD: your-app-password
      FROM_EMAIL: your-email@gmail.com
      FROM_NAME: BGG 設計師追蹤
      # PostgreSQL 啟動等待配置 - 減少初始等待時間
      POSTGRES_STARTUP_WAIT: 10
      # 跳過模組級初始化，讓應用快速啟動
      SKIP_MODULE_DB_INIT: 1
    dependencies:
      - postgresql
    wait_for:
      - postgresql
    healthcheck:
      endpoint: /health/quick
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    volumes:
      - name: reports
        mount: /app/frontend/public/outputs

volumes:
  reports: