services:
  postgresql:
    type: postgresql

  app:
    type: python
    build:
      command: pip install -r requirements.txt
    start:
      command: gunicorn --bind 0.0.0.0:$PORT --timeout 300 --workers 1 --max-requests 1000 --preload start_simple:app
    env:
      PORT: 5000
      FLASK_ENV: production
      TZ: Asia/Taipei
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: your-secure-password-here
      SECRET_KEY: your-secret-key-here
      DATABASE_URL: ${POSTGRES_CONNECTION_STRING}
      OPENAI_API_KEY: your-openai-api-key-here
      CRON_SECRET_TOKEN: your-cron-secret-token-here
    dependencies:
      - postgresql
    healthcheck:
      endpoint: /health
      interval: 120s
      timeout: 60s
      retries: 10
      start_period: 300s
    volumes:
      - name: reports
        mount: /app/frontend/public/outputs

volumes:
  reports: