services:
  database:
    type: postgresql

  app:
    type: python
    build:
      command: pip install -r requirements.txt
    start:
      command: python start.py
    env:
      PORT: 5000
      FLASK_ENV: production
      TZ: Asia/Taipei
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: your-secure-password-here
      SECRET_KEY: your-secret-key-here
    healthcheck:
      endpoint: /health
      interval: 30s
      timeout: 10s
      retries: 3

  scheduler:
    type: python
    build:
      command: pip install -r requirements.txt
    start:
      command: python scheduler.py
    env:
      FLASK_ENV: production
      TZ: Asia/Taipei