name: Dynamic BGG Report Generation

on:
  schedule:
    # 多個時間選項，預設每日台北時間 07:00 (UTC 23:00)
    - cron: '0 23 * * *'  # 23:00 UTC = 07:00 台北時間
    # 備用時間：可手動啟用其他時間
    # - cron: '0 1 * * *'   # 01:00 UTC = 09:00 台北時間
    # - cron: '0 9 * * *'   # 09:00 UTC = 17:00 台北時間
  workflow_dispatch:
    inputs:
      custom_time:
        description: '自定義執行時間 (格式: HH:MM)'
        required: false
        default: '23:00'

jobs:
  generate-report:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Validate inputs (secrets)
      env:
        ZEABUR_URL: ${{ secrets.ZEABUR_APP_URL }}
        CRON_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
      run: |
        if [ -z "${ZEABUR_URL:-}" ]; then
          echo "❌ Missing required Secret: ZEABUR_APP_URL"
          echo "Please set ZEABUR_APP_URL in Settings → Secrets and variables → Actions"
          exit 2
        fi
        if [ -z "${CRON_TOKEN:-}" ]; then
          echo "❌ Missing required Secret: CRON_SECRET_TOKEN"
          echo "Please set CRON_SECRET_TOKEN in Settings → Secrets and variables → Actions"
          exit 2
        fi

    - name: Trigger BGG Report Generation
      env:
        ZEABUR_URL: ${{ secrets.ZEABUR_APP_URL }}
        CRON_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
      shell: bash
      run: |
        set -u
        BASE_URL="${ZEABUR_URL%/}"
        TARGET_URL="${BASE_URL}/api/cron-trigger"

        echo "Triggering BGG report generation..."
        echo "Target URL: ${TARGET_URL}"
        echo "Time: $(date -u) UTC"

        # Allow capturing curl error codes without immediately failing the step
        set +e
        http_status=$(curl -sS -w "%{http_code}" -o /tmp/response.json \
          -X POST \
          -H "Authorization: Bearer ${CRON_TOKEN}" \
          -H "Content-Type: application/json" \
          "${TARGET_URL}")
        curl_exit=$?
        set -e

        echo "curl exit code: ${curl_exit}"
        echo "HTTP status code: ${http_status}"
        echo "Response content:"
        cat /tmp/response.json || true

        if [ ${curl_exit} -ne 0 ]; then
          echo "❌ curl execution failed (exit ${curl_exit}). Common causes: missing/invalid URL, DNS resolution failure, or service not running."
          echo "Please verify ZEABUR_APP_URL is correct (must include http(s):// and point to your deployment)."
          exit 3
        fi

        if [ "${http_status}" != "200" ]; then
          echo "❌ Report generation trigger failed"
          exit 1
        fi

        echo "✅ Report generation triggered successfully"