name: Update Followed Creators

on:
  schedule:
    # 每日 16:00 UTC (台北時間 00:00) 執行
    - cron: '0 16 * * *'
  workflow_dispatch:
    inputs:
      manual_trigger:
        description: '手動觸發設計師更新'
        required: false
        default: 'manual'

jobs:
  update-creators:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - name: Validate environment secrets
      env:
        ZEABUR_URL: ${{ secrets.ZEABUR_APP_URL }}
        CRON_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
      run: |
        if [ -z "${ZEABUR_URL:-}" ]; then
          echo "❌ 缺少必需的 Secrets: ZEABUR_APP_URL"
          echo "請到 Settings → Secrets and variables → Actions 設定 ZEABUR_APP_URL。"
          exit 2
        fi
        if [ -z "${CRON_TOKEN:-}" ]; then
          echo "❌ 缺少必需的 Secrets: CRON_SECRET_TOKEN"
          echo "請到 Settings → Secrets and variables → Actions 設定 CRON_SECRET_TOKEN。"
          exit 2
        fi

    - name: Trigger creator updates on Zeabur
      env:
        ZEABUR_URL: ${{ secrets.ZEABUR_APP_URL }}
        CRON_TOKEN: ${{ secrets.CRON_SECRET_TOKEN }}
      shell: bash
      run: |
        set -u
        BASE_URL="${ZEABUR_URL%/}"
        WAKE_URL="${BASE_URL}/"
        UPDATE_URL="${BASE_URL}/api/cron-update-creators"
        
        echo "🚀 Starting creator update process..."
        echo "Base URL: ${BASE_URL}"
        echo "Time: $(TZ='Asia/Taipei' date '+%a %b %d %H:%M:%S %Z %Y') (Taipei Time)"

        # Function to make HTTP request with detailed logging
        make_request() {
          local url="$1"
          local method="${2:-GET}"
          local description="$3"
          
          echo "📡 ${description}..."
          echo "  URL: ${url}"
          echo "  Method: ${method}"
          
          set +e
          if [ "$method" = "POST" ]; then
            http_status=$(curl -sS -w "%{http_code}" -o /tmp/response.json \
              --connect-timeout 30 --max-time 600 \
              -X POST \
              -H "Authorization: Bearer ${CRON_TOKEN}" \
              -H "Content-Type: application/json" \
              "${url}")
          else
            http_status=$(curl -sS -w "%{http_code}" -o /tmp/response.json \
              --connect-timeout 30 --max-time 600 \
              "${url}")
          fi
          curl_exit=$?
          set -e
          
          echo "  Exit code: ${curl_exit}"
          echo "  HTTP status: ${http_status}"
          echo "  Response:"
          cat /tmp/response.json 2>/dev/null || echo "    (no response content)"
          echo ""
          
          return $curl_exit
        }

        # Step 1: Wake up the application
        echo "🔥 Step 1: Waking up application..."
        if make_request "${WAKE_URL}" "GET" "Wake up application"; then
          if [ "${http_status}" = "200" ] || [ "${http_status}" = "302" ] || [ "${http_status}" = "301" ]; then
            echo "✅ Application is responding"
          else
            echo "⚠️  Application responded with status ${http_status}, but continuing..."
          fi
        else
          echo "⚠️  Wake up request failed, but continuing anyway..."
        fi

        # Step 2: Wait for application to fully start
        echo "⏳ Step 2: Waiting 30 seconds for application to fully initialize..."
        sleep 30

        # Step 3: Trigger creator updates with retry logic
        echo "👥 Step 3: Triggering creator updates..."
        
        MAX_RETRIES=3
        RETRY_DELAY=60
        
        for attempt in $(seq 1 $MAX_RETRIES); do
          echo "🔄 Attempt ${attempt}/${MAX_RETRIES}:"
          
          if make_request "${UPDATE_URL}" "POST" "Trigger creator updates"; then
            if [ "${http_status}" = "200" ]; then
              echo "✅ Creator updates triggered successfully!"
              exit 0
            elif [ "${http_status}" = "502" ] || [ "${http_status}" = "503" ] || [ "${http_status}" = "504" ]; then
              echo "⚠️  Server error (${http_status}) - application might still be starting up..."
              if [ $attempt -lt $MAX_RETRIES ]; then
                echo "💤 Waiting ${RETRY_DELAY} seconds before retry..."
                sleep $RETRY_DELAY
                continue
              fi
            else
              echo "❌ Request failed with status ${http_status}"
              break
            fi
          else
            echo "❌ Request failed with curl exit code ${curl_exit}"
            if [ $attempt -lt $MAX_RETRIES ]; then
              echo "💤 Waiting ${RETRY_DELAY} seconds before retry..."
              sleep $RETRY_DELAY
              continue
            fi
          fi
        done

        echo "❌ Creator updates failed after ${MAX_RETRIES} attempts"
        echo "💡 Troubleshooting tips:"
        echo "  - Check if ZEABUR_APP_URL is correct and includes http(s)://"
        echo "  - Verify CRON_SECRET_TOKEN matches your application configuration"
        echo "  - Ensure your Zeabur application is running and not crashed"
        echo "  - Check application logs in Zeabur dashboard"
        exit 1